"""empty message

Revision ID: 786493e53265
Revises: 9bf56addac5f
Create Date: 2023-11-14 20:39:34.569046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786493e53265'
down_revision = '9bf56addac5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
